### ISSUE TITLE
Add `--help` option to nextflow_conversion branch

### ISSUE THREAD

**Issue by hyunhwan-bcm** [LiuzLab/AI_MARRVEL#47]
## Description
We need to implement a `--help` option for the Nextflow script in the `nextflow_conversion` branch. This will provide users with information about the pipeline's usage, available parameters, and their descriptions.

## Proposed Implementation
1. Add a new process or function to handle the `--help` option.
2. When `--help` is invoked, display information about:
   - Basic usage
   - Input parameters (e.g., `params.input_vcf`, `params.input_hpo`, `params.run_id`)
   - Output directories and files
   - Reference files and their purposes
   - Brief descriptions of main processes (e.g., VCF processing, annotation, feature engineering, prediction)

## Example Help Output
```
Usage: nextflow run main.nf [options]

Options:
  --input_vcf           Path to input VCF file
  --input_hpo           Path to input HPO file
  --run_id              Unique identifier for this run
  --ref_ver             Reference genome version (hg38 or hg19)
  --outdir              Output directory
  --no_filter_exonic    Skip exonic filtering (default: false)

Reference Files:
  --ref_loc             Path to reference location file
  --ref_to_sym          Path to reference to symbol file
  --ref_sorted_sym      Path to reference sorted symbol file
  --ref_exonic_filter_bed  Path to exonic filter BED file

VEP Annotation:
  --vep_dir_cache       Path to VEP cache directory
  --vep_dir_plugins     Path to VEP plugins directory
  --vep_custom_gnomad   Path to custom gnomAD file for VEP
  --vep_custom_clinvar  Path to custom ClinVar file for VEP
  --vep_custom_hgmd     Path to custom HGMD file for VEP

(Add more parameters as needed)

For detailed information about each process, please refer to the documentation.
```

## Tasks
- [ ] Implement `--help` option in the main Nextflow script
- [ ] Generate comprehensive help text covering all important parameters and processes
- [ ] Ensure help text is properly formatted and easy to read
- [ ] Test the `--help` option to verify it displays correctly
- [ ] Update documentation to mention the new `--help` option

## Additional Notes
- Consider using Nextflow's built-in parameter validation and help generation features if available.
- Ensure the help text is kept up-to-date as the pipeline evolves.

**Comment by ZaahidShaik** [comment]
Made [PR](https://github.com/LiuzLab/AI_MARRVEL/pull/51) for this issue.
