### ISSUE TITLE
Implement parameter validation for all required parameters

### ISSUE THREAD

**Issue by hyunhwan-bcm** [LiuzLab/AI_MARRVEL#49]
## Description
We need to add a validation step at the beginning of our Nextflow pipeline to ensure that all required parameters are declared. This will help prevent runtime errors and provide clear feedback to users when necessary parameters are missing.

## Proposed Implementation

1. Create a new process or function for parameter validation
2. Check all required parameters
3. Provide clear error messages for any missing parameters
4. (Optional) Implement type checking and value validation for certain parameters

## Required Parameters to Check

Based on the provided Nextflow script, here's a non-exhaustive list of parameters that should be checked:

- `params.input_vcf`
- `params.input_hpo`
- `params.run_id`
- `params.ref_ver`
- `params.outdir`
- `params.ref_loc`
- `params.ref_to_sym`
- `params.ref_sorted_sym`
- `params.ref_exonic_filter_bed`
- `params.vep_dir_cache`
- `params.vep_dir_plugins`
- `params.vep_custom_gnomad`
- `params.vep_custom_clinvar`
- `params.vep_custom_hgmd`
- `params.vep_plugin_revel`
- `params.vep_plugin_spliceai_snv`
- `params.vep_plugin_spliceai_indel`
- `params.vep_plugin_cadd`
- `params.vep_plugin_dbnsfp`
- `params.vep_idx`

(Note: This list may not be complete and should be reviewed to ensure all required parameters are included)

## Example Implementation

```nextflow
def validateParameters() {
    def requiredParams = [
        'input_vcf', 'input_hpo', 'run_id', 'ref_ver', 'outdir',
        'ref_loc', 'ref_to_sym', 'ref_sorted_sym', 'ref_exonic_filter_bed',
        'vep_dir_cache', 'vep_dir_plugins', 'vep_custom_gnomad',
        'vep_custom_clinvar', 'vep_custom_hgmd', 'vep_plugin_revel',
        'vep_plugin_spliceai_snv', 'vep_plugin_spliceai_indel',
        'vep_plugin_cadd', 'vep_plugin_dbnsfp', 'vep_idx'
    ]

    def missingParams = []

    requiredParams.each { param ->
        if (!params.containsKey(param) || params[param] == null || params[param].toString().trim().isEmpty()) {
            missingParams.add(param)
        }
    }

    if (missingParams.size() > 0) {
        error """
        The following required parameters are missing:
        ${missingParams.join(', ')}
        
        Please provide values for these parameters and run the pipeline again.
        """
    }

    // Additional type and value checks can be added here
    if (params.ref_ver != 'hg38' && params.ref_ver != 'hg19') {
        error "ref_ver must be either 'hg38' or 'hg19'. Provided value: ${params.ref_ver}"
    }

    // Add more specific checks as needed
}

workflow {
    // Call the validation function at the start of the workflow
    validateParameters()

    // Rest of the workflow...
}
```

## Tasks
- [ ] Create a `validateParameters()` function or process
- [ ] Identify all required parameters in the pipeline
- [ ] Implement checks for each required parameter
- [ ] Add type and value validation for parameters where applicable
- [ ] Provide clear, informative error messages for missing or invalid parameters
- [ ] Integrate the validation step at the beginning of the main workflow
- [ ] Test the validation with various scenarios (all parameters present, missing parameters, invalid values)
- [ ] Update documentation to reflect the new parameter validation

## Additional Considerations
- Consider using Nextflow's built-in parameter validation features if available
- Group related parameters for easier management and validation
- Provide suggestions or default values in error messages where appropriate
- Consider adding warnings for optional parameters that are not set but might be important
