### ISSUE TITLE
 Implement data dependency checksum verification

### ISSUE THREAD

**Issue by hyunhwan-bcm** [LiuzLab/AI_MARRVEL#53]
## Description
We need to implement a checksum verification system for our data dependencies to ensure data integrity. This system should check the checksum of data dependencies by default, with an option to skip this check. We'll need to create, store, and verify checksums for both the internal version and the free version of our data.

## Proposed Implementation
1. Implement checksum verification as a default step in the pipeline
2. Add a `--skip_data_checksum` option to bypass the verification
3. Create a checksum file in the `ref_dir` if it doesn't exist
4. Store prepared checksum values for internal and free versions
5. Verify checksums against the prepared values without recreating them

### 1. Checksum Verification Process

Create a new process in the Nextflow script to handle checksum verification:

```nextflow
process VERIFY_DATA_CHECKSUMS {
    input:
    path ref_dir

    output:
    val true

    when:
    !params.skip_data_checksum

    script:
    """
    check_sum_program --ref_dir $ref_dir
    """
}
```

### 2. Update Configuration

Add the following to your Nextflow configuration file (`nextflow.config`):

```nextflow
params {
    skip_data_checksum = false
    internal_checksums = "/path/to/internal_checksums.json"
    free_checksums = "/path/to/free_checksums.json"
}
```

### 3. Update Main Workflow

Modify the main workflow to include the checksum verification:

```nextflow
workflow {
    if (!params.skip_data_checksum) {
        VERIFY_DATA_CHECKSUMS(params.ref_dir)
    }
    
    // Rest of the workflow
    // ...
}
```

## Tasks
- [ ] Implement the `VERIFY_DATA_CHECKSUMS` process in the Nextflow script
- [ ] Update the `nextflow.config` file to include the new parameters
- [ ] Modify the main workflow to include the checksum verification step
- [ ] Generate checksum files for both internal and public versions of the data
- [ ] Test the checksum verification with both matching and mismatching data
- [ ] Update the documentation to explain the new checksum verification feature and the `--skip_data_checksum` option
- [ ] Implement error handling and user-friendly messages for checksum mismatches

## Additional Notes
- Ensure that the checksum verification process is efficient and doesn't significantly impact the pipeline's runtime
- Consider using a faster hashing algorithm if MD5 proves to be too slow for large datasets
- Implement a way to update the checksum files when the data dependencies are legitimately updated
- Provide clear instructions in the documentation on what to do if a checksum mismatch is detected

**Comment by hyunhwan-bcm** [comment]
@sasidharPasupuleti any update?

**Comment by jylee-bcm** [comment]
If we should check VEP directory as well, I think any checksum idea including DVC is not a good approach. Because we cannot perform the verification whenever we run the ppeline. 

Instead, how about using "tree -sJ" command, which takes only 0.6 second. Even though it's not technically integrity check but it's a **"sanity checking"** which is enough to prevent the situation of using outdated data directory.

### `tree -SJ` Example.
```tree
[
  {"type":"directory","name":"data/","size":4096,"contents":[
    {"type":"directory","name":"annotate","size":4096,"contents":[
      {"type":"directory","name":"anno_hg19","size":4096,"contents":[
        {"type":"file","name":"decipher.csv","size":4945374},
        {"type":"file","name":"dgv.csv","size":171821810},
        {"type":"file","name":"gene_clinvar.csv","size":1852532},
        {"type":"file","name":"gene_omim.json","size":44635501},
        {"type":"file","name":"gnomad.v2.1.1.lof_metrics.by_gene.txt","size":13203203},
        {"type":"file","name":"omim_alleric_variants.json","size":4617170}
...
```
